version: '3'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    networks:
      macvlan_network:
        ipv4_address: 172.16.44.8
      default:

volumes:
  open-webui:

networks:
  macvlan_network:
    name: 'macvlan_network'
    external: true
